package frsf.isi.died.tp.estructuras;

public enum TipoNodo {
	TITULO, METADATO_MATERIAL, METADATO_CAPITULO, AUTOR, SECCION, PARRAFO, CAPITULO, EDITORIAL, RESUMEN, PALABRA_CLAVE, FECHA_PUBLICACION, SITIO, EJERCICIOS;
}
